repos:
  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.13.0
  #   hooks:
  #   - id: markdownlint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-toml
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
    # Run linter
  - id: ruff
    types_or: [python, pyi]
    args: [--fix]
    # Run formatter
  - id: ruff-format
    types_or: [python, pyi]
