repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: mixed-line-ending
    - id: trailing-whitespace
    - id: check-toml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
    # Run linter
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run formatter
    - id: ruff-format
      types_or: [ python, pyi ]
