[project]
name = "dot.py"
version = "1.1.0"
authors = [
  { name="Vincent QB", email="vincentqb@gmail.com" },
]
description = "dot.py is a minimalist python script for managing dotfiles via symbolic links."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.optional-dependencies]
build = [
    "build",
]
test = [
    "pytest",
]
lint = [
    "flake8",
    "ruff",
]

[project.scripts]
"dot.py" = "_dot:dot_from_args"

[project.urls]
"Homepage" = "https://github.com/vincentqb/dot.py/"
"Bug Tracker" = "https://github.com/vincentqb/dot.py/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-include = ["dot.py", "_dot.py"]

[tool.ruff]
line-length = 120
