[project]
name = "dot.py"
version = "1.2.0"
authors = [{ name = "Vincent QB", email = "vincentqb@gmail.com" }]
description = "dotpy is a minimalist python script for managing dotfiles via symbolic links."
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]

[project.optional-dependencies]
dev = ["codespell", "coverage", "pytest", "ruff>=0.5.3"]

[project.scripts]
"dotpy" = "dot.__main__:dot_from_args"

[project.urls]
"Homepage" = "https://github.com/vincentqb/dotpy/"
"Bug Tracker" = "https://github.com/vincentqb/dotpy/"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
only-include = ["dot"]

[tool.coverage.report]
fail_under = 90

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["C901", "I", "RUF022"]
