name: test and publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install
      run: |
        pip install --upgrade pip
        pip install .[dev]
    - name: Lint
      run: |
        codespell .
        ruff check .
        ruff format . --diff
    - name: Test
      run: |
        coverage run -m pytest
        coverage report

  publish:
    name: Publish
    environment:
      name: pypi
      url: https://pypi.org/project/dot.py/
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install build
    - name: Build
      run: |
        python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
