name: test and publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

permissions:
  contents: read

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        : # https://github.com/pypa/pip/issues/11440#issuecomment-1826187421
        pip install --upgrade git+https://github.com/jazzband/pip-tools
        pip-compile --all-build-deps --all-extras --output-file=requirements.txt --strip-extras pyproject.toml
        pip install -r requirements.txt
    - name: Lint
      run: ruff .
    - name: Build
      run: python -m build
    - name: Install
      run: pip install dist/*.whl
    - name: Test
      run: python -m pytest

  publish:
    name: Publish
    environment:
      name: pypi
      url: https://pypi.org/p/dotpy
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        : # https://github.com/pypa/pip/issues/11440#issuecomment-1826187421
        pip install --upgrade git+https://github.com/jazzband/pip-tools
        pip-compile --all-build-deps --output-file=requirements.txt --strip-extras pyproject.toml
        pip install -r requirements.txt
    - name: Build
      run: python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
