name: test and publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

permissions:
  contents: read

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Spelling
      run: codespell .
    - name: Lint
      run: |
        ruff check .
        ruff format . --diff
    - name: Test
      run: python -m pytest

  publish:
    name: Publish
    environment:
      name: pypi
      url: https://pypi.org/p/dotpy
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build
      run: python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
