name: test and publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

permissions:
  contents: read

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Generate requirements files
      run: |
        python -m pip install --upgrade pip
        pip install tomli
        python tools/generate_requirements.py
    - name: Install dependencies
      run: |
        pip install -r requirements/build.txt
        pip install -r requirements/test.txt
        pip install -r requirements/lint.txt
    - name: Lint
      run: |
        ruff .
    - name: Build with pip
      run: |
        pip install .
    - name: Test
      run: |
        python -m pytest
    - name: Build with build
      run: |
        python -m build

  publish:
    name: Publish
    environment:
      name: pypi
      url: https://pypi.org/p/dot.py
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Generate requirements files
      run: |
        python -m pip install --upgrade pip
        pip install tomli
        python tools/generate_requirements.py
    - name: Install dependencies
      run: |
        pip install -r requirements/build.txt
    - name: Build
      run: |
        python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
