name: test and publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v3
    - name: Set up Python
      run: |
        uv python install
        uv venv
        source .venv/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
    - name: Install package
      run: |
        uv pip install .[dev]
    - name: Check lint
      run: |
        codespell .
        ruff check .
        ruff format . --diff
    - name: Check typing
      run: |
        pytype
    - name: Test
      run: |
        coverage run -m pytest
        coverage report

  publish:
    name: Publish
    environment:
      name: pypi
      url: https://pypi.org/project/dot.py/
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: test
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@v3
    - name: Build
      run: |
        uv build
    - name: Validate Tag
      run: |
        git describe --tags --abbrev=0
        uv python install
        uv venv
        source .venv/bin/activate
        uv pip install dist/*.whl
        python3 validate_version.py
    - name: Publish
      run: |
        echo
    # run: uv publish -t ${{ secrets.PYPI_TOKEN }}
