name: test and publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      run: uv python install
    - name: Lint
      run: |
        uv tool run codespell .
        uv tool run ruff check .
        uv tool run ruff format . --diff
    - name: Test
      run: |
        uv tool run --with "pytest" coverage run -m pytest
        uv tool run coverage report
    - name: Build
      run: uv build

  publish:
    name: Publish
    environment:
      name: pypi
      url: https://pypi.org/project/dot.py/
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      run: uv python install
    - name: Build
      run: uv build
    - name: Publish
      run: uv publish -t ${{ secrets.PYPI_TOKEN }}
